### PR TITLE
disable curl ssl verify

### LINKED ISSUE #47: SVGs don't come up in production
I think the function we use to pull svg data is old and doesn't work in newer versions of php

### PR DESCRIPTION
**Pull request by mikeyrayvon**
fix #47

### CODE REVIEW

File: lib/functions-utility.php [hunk 1]
```diff
@@ -7,6 +7,7 @@ function url_get_contents($Url) {
   }
 
   $ch = curl_init();
+  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
```
Comment (varffs) [inline lib/functions-utility.php:10]: I guess this is only sketchy if we use the function wrong ourselves. So it is ok.

**Review by varffs — APPROVED** [review]
I'm assuming we know this is the issue with the server?
